anydrive_setup:
  ethercat_master_s:
    Master1:
      name: MyDynaaarmEthercatMaster
      ethercat_bus: enx606d3cd88890
      time_step: 0.0025
      update_rate_too_low_warn_threshold: 50.0
      # periodically mentionors the bus application layer state and ethercat state machine state
      # prints some logs in case something falls out of operational.
      bus_diagnosis: true
      # saves a diagnosis log to ~/ethercat_master/<data_time>.log
      # plots can be created with a python script in the folder
      error_counter_log: true
  ethercat_devices:
    DynaDrive1:
      type: Anydrive
      communication:
        ethercat_address: 1
        ethercat_bus: enx606d3cd88890
        ethercat_pdo_type: A
      configuration:
        max_current: 5.0
        max_freeze_current: 5.0
        dgainFilterCutoffFrequency: 30.0
        direction: -1
        goal_states:
          shutdown: MotorOp
          startup: MotorOp
        joint_position_limits:
          hard:
            max: 4.6
            min: -4.6
          sdk:
            max: 0.0
            min: 0.0
          soft:
            max: 4.5
            min: -4.5
        max_motor_velocity: 10.0
      id: 0
    # DynaDrive2:
    #   type: Anydrive
    #   communication:
    #     ethercat_address: 2
    #     ethercat_bus: enx606d3cd88890
    #     ethercat_pdo_type: A
    #   configuration:
    #     max_current: 5.0
    #     max_freeze_current: 5.0
    #     dgainFilterCutoffFrequency: 30.0
    #     direction: -1
    #     goal_states:
    #       shutdown: MotorOp
    #       startup: ControlOp
    #     joint_position_limits:
    #       hard:
    #         max: 4.6
    #         min: -4.6
    #       sdk:
    #         max: 0.0
    #         min: 0.0
    #       soft:
    #         max: 4.5
    #         min: -4.5
    #     max_motor_velocity: 10.0
    #   id: 0
